name: nutri_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.0
  fl_chart: ^0.71.0
  lucide_icons_flutter: ^3.0.0
  logger: ^2.0.2
  #sqflite: ^2.0.0
  #sqflite_common_ffi: ^2.0.3
  #sqflite_common_ffi_web: ^1.0.0
  path_provider: ^2.1.1
  path: ^1.8.0
  intl: ^0.20.2
  diacritic: ^0.1.3
  http: ^1.1.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.1.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/food_data.json
    - assets/env

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
